template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "hind1269"
__REPO__ = "lang-hin"
__UND2C__ = "hi"
__UNDEFINED__ = "Hindi"
__UND__ = "hin"
